CREATE TABLE Mineradores (
	Id INTEGER PRIMARY KEY AUTOINCREMENT,
	IdExterno INT NULL,
	Localizacao NVARCHAR (4000) NOT NULL,
	Parametros NVARCHAR (4000) NULL,
	Ativo BIT NOT NULL DEFAULT 0,
	DataCriacao DateTime NOT NULL,
	DataAlteracao DateTime NOT NULL
);

CREATE TABLE Comandos (
	Id INTEGER PRIMARY KEY AUTOINCREMENT,
	Comandos NVARCHAR (4000) NOT NULL,
	PreMineracao BIT NOT NULL DEFAULT 0,
	PosMineracao BIT NOT NULL DEFAULT 0,
	Ativo BIT NOT NULL DEFAULT 0,
	DataCriacao DateTime NOT NULL,
	DataAlteracao DateTime NOT NULL
);

CREATE TABLE Logs (
	Id INT PRIMARY KEY AUTOINCREMENT,
	
);