CREATE TABLE Miners (
	Id INTEGER PRIMARY KEY AUTOINCREMENT,
	CoinId INTEGER NULL,

	Name NVARCHAR (200) NULL,
	Location NVARCHAR (4000) NOT NULL,

	Parameters NVARCHAR (4000) NULL,
	Active BIT NOT NULL DEFAULT 0,
	
	CreatedDate DateTime NOT NULL DEFAULT CURRENT_TIMESTAMP,
	UpdatedDate DateTime NOT NULL DEFAULT CURRENT_TIMESTAMP,
	
	FOREIGN KEY (CoinId) REFERENCES Coins (Id)
);

CREATE TABLE Commands (
	Id INTEGER PRIMARY KEY AUTOINCREMENT,
	Commands NVARCHAR (4000) NOT NULL,
	
	PreMining BIT NOT NULL DEFAULT 0,
	AfterMining BIT NOT NULL DEFAULT 0,
	
	Active BIT NOT NULL DEFAULT 0,
	
	CreatedDate DateTime NOT NULL DEFAULT CURRENT_TIMESTAMP,
	UpdatedDate DateTime NOT NULL DEFAULT CURRENT_TIMESTAMP 
);

CREATE TABLE Coins (
	Id INTEGER PRIMARY KEY AUTOINCREMENT,
	ExternalId INT NULL,
	
	Name NVARCHAR (500) NULL,
	ExternalName NVARCHAR (500) NULL
);

--CREATE TABLE Mineradores_Coins (
--	IdMinerador INTEGER,
--	CoinId INTEGER,

--	PRIMARY KEY (IdMinerador, CoinId),
--	FOREIGN KEY (IdMinerador) REFERENCES Mineradores(Id),
--	FOREIGN KEY (CoinId) REFERENCES Coins(Id)
--);